sudo: false
language: java
env:
  - NODE_VERSION=10
jdk:
  - openjdk8
before_install:
  - nvm install $NODE_VERSION
  - mkdir registry-integration
  - wget https://github.com/sofastack/sofa-registry/releases/download/v5.2.1/registry-integration.tgz
  - tar -zxvf registry-integration.tgz -C registry-integration
  - sh registry-integration/bin/startup.sh
  - npm i npminstall -g
  - java -version
install:
  - npminstall
  - node test/healthcheck.js
script:
  - npm run ci
after_script:
  - npminstall codecov && codecov
  - sh registry-integration/bin/shutdown.sh
